# Generated by Django 4.2.6 on 2024-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='stories/pdfs/')),
                ('audio_files', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
            ],
        ),
    ]
