# Generated by Django 4.2.6 on 2024-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasapp', '0002_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audio_files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
