# Generated by Django 4.2.6 on 2024-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasapp', '0003_alter_story_audio_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
